# Basic OpenTelemetry Collector configuration using GenAI processor with remote LiteLLM
# This configuration connects to a remote LiteLLM gateway instance

receivers:
  filelog:
    include: ["/tmp/sample_logs.json"]
    start_at: beginning
    multiline:
      # Read the entire JSON array as one log entry
      line_start_pattern: '^\['
    # Remove JSON parser since we want the raw array as text for GenAI processing

processors:
  genai:
    # Update this to your remote LiteLLM gateway URL
    endpoint: ""
    
    # Optional: Add API key if your remote gateway requires authentication
    api_key: ""
    
    model: "gpt-4o-mini"
    system_prompt: |
      You are a log processing assistant. You will receive a JSON array containing multiple log entries.
      Split this JSON array into individual JSON objects and return ONLY the JSON objects.
      
      CRITICAL FORMATTING RULES:
      1. Return each complete JSON object on a separate line as COMPACT JSON (no formatting, no indentation)
      2. Prepend the size of each log entry in bytes as a new field "size_bytes"
      3. Do not include any explanations, comments, or markdown formatting
      4. Do not include the array brackets [ ]
      5. Each line must be a valid, complete JSON object in compact format
      6. Preserve all original fields and values exactly as they appear
      7. EXAMPLE OUTPUT FORMAT:
         {"timestamp":"2025-08-21T10:30:00Z","level":"INFO","service":"user-api","message":"User login successful"}
         {"timestamp":"2025-08-21T10:30:15Z","level":"WARN","service":"user-api","message":"Rate limit approaching"}
    user_prompt: |
      Split this JSON array into individual JSON objects, one per line in compact format (no indentation):
      
      {{.body}}
    max_tokens: 2000
    temperature: 0.0
    timeout: 30s
    response_field: "individual_logs"
    filter_regex: ".*"  # Process all logs

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [genai]
      exporters: [debug]

  telemetry:
    logs:
      level: info
    metrics:
      level: basic

