name: Generate OpenTelemetry Collector Sources

inputs:
  skip-cache-restore-on-hit:
    description: |
      Skips restoring the cache when there is a cache hit for the primary cache
      key. Set to "true" to enable.
    required: false

outputs:
  cache-hit:
    description: A boolean value to indicate an exact match was found for the primary key
    value: ${{ steps.sources-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # Fix slow Go compile and cache restore
    # See https://github.com/actions/setup-go/pull/515
    - name: Set Go cache environment variables (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo 'GOCACHE=D:\gocache' >> $GITHUB_ENV
        echo 'GOMODCACHE=D:\gomodcache' >> $GITHUB_ENV
        echo 'GOTMPDIR=D:\gotmp' >> $GITHUB_ENV
        mkdir -p /d/gocache
        mkdir -p /d/gomodcache
        mkdir -p /d/gotmp

    - name: Setup Go (Official distribution)
      if: inputs.distribution != 'microsoft'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.version }}
        cache: false

    - name: Setup Go (Microsoft distribution)
      if: inputs.distribution == 'microsoft'
      uses: ./.github/actions/setup-microsoft-go
      with:
        version: ${{ inputs.version }}

    - name: Set Go environment outputs
      id: go-env
      shell: bash
      run: |
        echo "go-arch=$(go env GOARCH)" >> $GITHUB_OUTPUT
        echo "go-cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "go-host-arch=$(go env GOHOSTARCH)" >> $GITHUB_OUTPUT
        echo "go-host-os=$(go env GOHOSTOS)" >> $GITHUB_OUTPUT
        echo "go-mod-cache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
        echo "go-os=$(go env GOOS)" >> $GITHUB_OUTPUT
        echo "go-path=$(go env GOPATH)" >> $GITHUB_OUTPUT
        echo "go-proxy=$(go env GOPROXY)" >> $GITHUB_OUTPUT
        echo "go-root=$(go env GOROOT)" >> $GITHUB_OUTPUT
        echo "go-tmp-dir=$(go env GOTMPDIR)" >> $GITHUB_OUTPUT
        echo "go-version=$(go env GOVERSION)" >> $GITHUB_OUTPUT
        go env

    - name: Set cache outputs
      id: go-cache-keys
      shell: bash
      env:
        BASE_KEY: go-cache
        DISTRIBUTION: ${{ inputs.distribution }}
      run: |
        distribution_key="${BASE_KEY}-${DISTRIBUTION}"
        runner_os_key="${distribution_key}-${RUNNER_OS}"
        full_key="${runner_os_key}-${{ hashFiles('**/*.sum') }}"

        echo "base=${BASE_KEY}" >> $GITHUB_OUTPUT
        echo "distribution=${distribution_key}" >> $GITHUB_OUTPUT
        echo "runner-os=${runner_os_key}" >> $GITHUB_OUTPUT
        echo "full=${full_key}" >> $GITHUB_OUTPUT

    - name: Cache OpenTelemetry Collector sources
      id: otelcol-sources-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.go-env.outputs.go-path }}/bin
          ${{ steps.go-env.outputs.go-mod-cache }}
          ${{ steps.go-env.outputs.go-cache }}
        key: ${{ steps.go-cache-keys.outputs.full }}
        lookup-only: ${{ inputs.skip-cache-restore-on-hit == 'true' }}
        restore-keys: |
          ${{ steps.go-cache-keys.outputs.runner-os }}-

    - name: Restore Go cache if no exact cache hit
      if: inputs.skip-cache-restore-on-hit == 'true' && steps.go-cache.outputs.cache-hit != 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ steps.go-env.outputs.go-path }}/bin
          ${{ steps.go-env.outputs.go-mod-cache }}
          ${{ steps.go-env.outputs.go-cache }}
        key: ${{ steps.go-cache-keys.outputs.full }}
        restore-keys: ${{ steps.go-cache-keys.outputs.runner-os }}-

    - name: Generate sources
      if: inputs.skip-cache-restore-on-hit == 'true' && steps.go-cache.outputs.cache-hit != 'true'
      working-directory: otelcolbuilder
      run: make generate-sources
