name: 'Build FIPS'
description: 'Build the otelcol-sumo FIPS binary'
inputs:
  go-version:
    description: 'The version of Go to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
