name: Setup Microsoft Distribution of Go

inputs:
  install-dir:
    description: The directory to install Go to.
    required: false
    default: D:\go
  version:
    description: The version of Go to install.
    required: true

outputs:
  go-cache:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Check Runner
      shell: bash
      run: |
        if [[ "${RUNNER_OS}" != "Windows" ]]; then
          echo "The Microsoft distribution of Go is only supported on Windows runners"
          exit 1
        fi

    - name: Set GitHub Path
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Create Go directory
      shell: pwsh
      run: |
        $installDir = "${{ inputs.install-dir }}"

        If (-not (Test-Path $installDir -PathType Container)) {
          New-Item -path $installDir -ItemType Directory
        }

    - name: Install Microsoft Distribution of Go
      shell: pwsh
      run: go-install.ps1 -Version "go${{ inputs.version }}" -InstallDir "${{ inputs.install-dir }}"
