run:
  timeout: 3m
  allow-parallel-runners: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: true

  gosimple:
    go: "1.16"

  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true

  unused:
    go: "1.16"

  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 185
    # tab width in spaces. Default to 1.
    tab-width: 8

linters:
  disable-all: false
  enable:
    - gofmt
    - deadcode
    - unused
    - errcheck
    - goimports
    - misspell
    - noctx
    - lll
  disable:
    - maligned
    - prealloc
  fast: false

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
