repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  -   id: check-json
  -   id: check-yaml
  -   id: double-quote-string-fixer
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
exclude: (.vscode|go.sum|go.mod)
