FROM mcr.microsoft.com/windows/servercore:ltsc2022
ARG BUILD_TAG=latest
ENV TAG $BUILD_TAG

ADD /otelcol-sumo.exe /otelcol-sumo.exe
ENTRYPOINT ["/otelcol-sumo.exe"]
CMD ["--config", "/etc/otel/config.yaml"]
