ARG BUILD_TAG
ARG REPO_URL=sumologic-otel-collector
ARG BUILD_ARCH

## Build RedHat compliant image
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10

ARG BUILD_TAG
ENV TAG $BUILD_TAG

ENV SUMMARY="UBI based sumologic-otel-collector" \
    DESCRIPTION="Sumo Logic Distribution for OpenTelemetry Collector is a Sumo Logic-supported distribution of the OpenTelemetry Collector. It is a single agent to send logs, metrics and traces to Sumo Logic."

LABEL name="sumologic-otel-collector" \
    vendor="Sumo Logic" \
    version="$BUILD_TAG" \
    release="0" \
    summary="$SUMMARY" \
    description="$DESCRIPTION" \
    io.k8s.description="$DESCRIPTION" \
    maintainer="collection@sumologic.com"

ADD https://raw.githubusercontent.com/SumoLogic/sumologic-otel-collector/main/LICENSE \
    /licenses/LICENSE

RUN microdnf update && microdnf install systemd && microdnf clean all


COPY otelcol-sumo /
# This shouldn't be necessary but sometimes we end up with execution bit not set
RUN chmod 755 /otelcol-sumo

ARG USER_UID=10001
USER ${USER_UID}
ENV HOME /etc/otel/

ENTRYPOINT ["/otelcol-sumo"]
CMD ["--config", "/etc/otel/config.yaml"]
