receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    # Change to `logLevel: info` for less noisy output from OtelCol
    logLevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      exporters: [logging]
