---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to install Sumo Logic Distro for OpenTelemetry on ECS in EC2 mode'
Parameters:
  IAMTaskRole:
    Description: Task attached IAM role
    Type: String
    Default: SumologicOTelColTaskRoleECSEC2
    ConstraintDescription: must be an existing IAM role which will be attached to EC2 instance.
  IAMExecutionRole:
    Description: Task Execution attached IAM role
    Type: String
    Default: SumologicOTelColExecutionRoleECSEC2
    ConstraintDescription: must be an existing IAM role which will be attached to EC2 instance.
  IAMPolicy:
    Description: IAM Role attached IAM Policy
    Type: String
    Default: SumologicOTelColPolicyECSEC2
    ConstraintDescription: Must be an existing IAM Managed Policy which will be attached to IAM Role.
  ClusterName:
    Type: String
    Description: Enter the name of your ECS cluster from which you want to collect telemetry data
  SumoOTelConfig:
    Type: AWS::SSM::Parameter::Value<String>
    Default: sumologic-otel-col-config
    Description: AWS SSM Parameter which contains OTel Collector config file
  SumologicReplicaServiceName:
    Type: String
    Default: sumologic-otel-col-svc-ecs-ec2
    Description: ECS Service Name
Resources:
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: sumologic-otel-ec2
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${IAMTaskRole}'
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${IAMExecutionRole}'
      ContainerDefinitions:
        - logConfiguration:
            logDriver: awslogs
            options:
              awslogs-create-group: 'True'
              awslogs-group: /ecs/sumologic-otel-collector
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
          portMappings:
            - hostPort: 4317
              protocol: tcp
              containerPort: 4317
            - hostPort: 4318
              protocol: tcp
              containerPort: 4318
            - hostPort: 8888
              protocol: tcp
              containerPort: 8888
          Command:
            - --config
            - env:OTEL_CONFIG_CONTENT
          Environment:
            - Name: OTEL_CONFIG_CONTENT
              Value: !Ref SumoOTelConfig
          Image: public.ecr.aws/sumologic/sumologic-otel-collector:0.86.0-sumo-0
          Name: sumologic-otel-collector
      RequiresCompatibilities:
        - EC2
      Cpu: 1024
      Memory: 2048
    DependsOn:
      - ECSTaskRole
      - ECSExecutionRole
  ECSReplicaService:
    Type: 'AWS::ECS::Service'
    Properties:
      TaskDefinition: !Ref ECSTaskDefinition
      Cluster: !Ref ClusterName
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      ServiceName: !Ref SumologicReplicaServiceName
    DependsOn:
      - ECSTaskDefinition
  ECSTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Allows ECS tasks to call AWS services on your behalf.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Ref IAMPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogStreams'
                  - 'logs:DescribeLogGroups'
                  - 'ssm:GetParameters'
                Resource: '*'
      RoleName: !Ref IAMTaskRole
  ECSExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: >-
        Allows ECS container agent makes calls to the Amazon ECS API on your
        behalf.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
      RoleName: !Ref IAMExecutionRole
