exporters:
    otlp:
        endpoint: localhost:1111
receivers:
    otlp:
        protocols:
            grpc: {}
            http: {}
service:
    pipelines:
        traces:
            exporters:
                - otlp
            processors: []
            receivers:
                - otlp
