dist:
  # name: otelcol-sumo # name of the binary produced. Optional, specified in Makefile for each platform.
  description: Sumo Logic OpenTelemetry Collector distribution

  # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  module: github.com/SumoLogic/sumologic-otel-collector

  # the OpenTelemetry Collector version to use as base for the distribution.
  otelcol_version: 0.36.0
  # the path to write the output (sources and binary).
  output_path: ./cmd

exporters:
  # Exporters with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/exporter/sumologicexporter v0.36.0"
    path: ./../pkg/exporter/sumologicexporter

  # Upstream exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/carbonexporter v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.36.0"

processors:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/cascadingfilterprocessor v0.36.0"
    path: ./../pkg/processor/cascadingfilterprocessor
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor v0.36.0"
    path: ./../pkg/processor/k8sprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sourceprocessor v0.36.0"
    path: ./../pkg/processor/sourceprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sumologicsyslogprocessor v0.36.0"
    path: ./../pkg/processor/sumologicsyslogprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/metricfrequencyprocessor v0.36.0"
    path: ./../pkg/processor/metricfrequencyprocessor

  # Upstream processors:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.36.0"

receivers:
  # Receivers with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/receiver/telegrafreceiver v0.36.0"
    path: ./../pkg/receiver/telegrafreceiver

  # Upstream receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/opencensusreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/udplogreceiver v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.36.0"

extensions:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/extension/sumologicextension v0.36.0"
    path: ./../pkg/extension/sumologicextension

  # Upstream receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.36.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.36.0"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage"


# Replacement paths are relative to the output_path (location of source files)
replaces:
  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver@v0.36.0 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza => github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza v0.36.0

  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor@v0.36.0 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/pkg/batchpersignal@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/pkg/batchpersignal => github.com/open-telemetry/opentelemetry-collector-contrib/pkg/batchpersignal v0.36.0

  # ----------------------------------------------------------------------------
  # Needed for telegrafreceiver
  - github.com/influxdata/telegraf => github.com/sumologic/telegraf v1.19.3-sumo-0

  # TODO: remove this when regexp log filtering is released upstream, e.g. this
  # PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5237
  # and when record level log filtering is available as implemented in here:
  # https://github.com/pmalek-sumo/opentelemetry-collector-contrib/commit/11de2c03d3dbbde2e73b8a816318a2515c843985
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/filterprocessor 11de2c03d3dbbde2e73b8a816318a2515c843985

  # Use features from branch:
  # https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/v0.36.0-routingprocessor-allow-routing-on-all-signals
  # This replacement should be removed when all the features from the branch are upstreamed.
  # One PR addressing the above can be found here:
  # * https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5694
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/routingprocessor 9c497458a97b5b6772915da177df6f8f5b67e1e2

  # TODO: remove this when fluentforwardreceiver support for complex object is accepted, merged and released upstream
  # PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5676
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver => github.com/SumoLogic/opentelemetry-collector-contrib/receiver/fluentforwardreceiver 975436eaca3e805571a96e3712530c4ff63a349d
