dist:
  # name: otelcol-sumo # name of the binary produced. Optional, specified in Makefile for each platform.
  description: Sumo Logic OpenTelemetry Collector distribution

  # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  module: github.com/SumoLogic/sumologic-otel-collector

  # the OpenTelemetry Collector version to use as base for the distribution.
  otelcol_version: 0.38.0
  # the path to write the output (sources and binary).
  output_path: ./cmd

exporters:
  # Exporters with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/exporter/sumologicexporter v0.38.0"
    path: ./../pkg/exporter/sumologicexporter

  # Upstream exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/carbonexporter v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.38.0"

processors:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/cascadingfilterprocessor v0.38.0"
    path: ./../pkg/processor/cascadingfilterprocessor
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor v0.38.0"
    path: ./../pkg/processor/k8sprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sourceprocessor v0.38.0"
    path: ./../pkg/processor/sourceprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sumologicsyslogprocessor v0.38.0"
    path: ./../pkg/processor/sumologicsyslogprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/metricfrequencyprocessor v0.38.0"
    path: ./../pkg/processor/metricfrequencyprocessor

  # Upstream processors:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.38.0"

receivers:
  # Receivers with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/receiver/telegrafreceiver v0.38.0"
    path: ./../pkg/receiver/telegrafreceiver

  # Upstream receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/opencensusreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/udplogreceiver v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.38.0"

extensions:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/extension/sumologicextension v0.38.0"
    path: ./../pkg/extension/sumologicextension

  # Upstream receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.38.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.38.0"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage"


# Replacement paths are relative to the output_path (location of source files)
replaces:
  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver@v0.37.1 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza => github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza  v0.38.0

  # ----------------------------------------------------------------------------
  # Needed for telegrafreceiver
  - github.com/influxdata/telegraf => github.com/SumoLogic/telegraf v1.20.2-sumo-0

  # TODO: remove this when:
  # - regexp log filtering is released upstream:
  #   PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5680
  # - record level log filtering is available upstream:
  #   commit: https://github.com/pmalek-sumo/opentelemetry-collector-contrib/commit/11de2c03d3dbbde2e73b8a816318a2515c843985
  # - expr log filtering is merged and released upstream:
  #   PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5680
  # - support for regexp for delete and hash actions for attribute attraction
  #   PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5750
  #
  # For now, cherry-picked changes are being used:
  # commit: https://github.com/SumoLogic/opentelemetry-collector-contrib/commit/af1f222dacd90b3baee67c935a12ca5b523c349c
  # branch: https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/v0.38.0-filterprocessor
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/filterprocessor 4e57c94574d31e2ef1df385167421e6c54d60d75
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal => github.com/SumoLogic/opentelemetry-collector-contrib/internal/coreinternal 4e57c94574d31e2ef1df385167421e6c54d60d75
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/attributesprocessor 4e57c94574d31e2ef1df385167421e6c54d60d75
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/resourceprocessor 4e57c94574d31e2ef1df385167421e6c54d60d75

  # TODO: remove this when:
  # - routing on resource attributes for traces is merged upstream and available in released version
  #   PR: https://github.com/SumoLogic/opentelemetry-collector-contrib/commit/6dc23bb08e41f434ec4cae5aea8e380d0766e455
  # - routing on resource attributes for all signals is merged upstream and available in released version
  #   branch: https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/v0.37.1-routingprocessor-allow-routing-on-all-signals
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/routingprocessor 6dc23bb08e41f434ec4cae5aea8e380d0766e455
