dist:
  name: otelcol-sumo
  description: Sumo Logic OpenTelemetry Collector distribution

  # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  module: github.com/SumoLogic/sumologic-otel-collector

  # the OpenTelemetry Collector version to use as base for the distribution.
  otelcol_version: 0.57.2
  # the path to write the output (sources and binary).
  output_path: ./cmd

exporters:
  # Exporters with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/exporter/sumologicexporter v0.0.0-00010101000000-000000000000"
    path: ./../pkg/exporter/sumologicexporter

  # Upstream exporters:

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.57.2
  - import: go.opentelemetry.io/collector/exporter/otlpexporter
    gomod: go.opentelemetry.io/collector v0.57.2
  - import: go.opentelemetry.io/collector/exporter/otlphttpexporter
    gomod: go.opentelemetry.io/collector v0.57.2

  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/carbonexporter v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.57.2"

processors:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/cascadingfilterprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/cascadingfilterprocessor
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/k8sprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sourceprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/sourceprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sumologicschemaprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/sumologicschemaprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sumologicsyslogprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/sumologicsyslogprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/metricfrequencyprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/metricfrequencyprocessor

  # Upstream processors:

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.57.2
  - import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
    gomod: go.opentelemetry.io/collector v0.57.2

  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatorateprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricsgenerationprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/schemaprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.57.2"

receivers:
  # Receivers with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/receiver/telegrafreceiver v0.0.0-00010101000000-000000000000"
    path: ./../pkg/receiver/telegrafreceiver

  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/receiver/rawk8seventsreceiver v0.0.0-00010101000000-000000000000"
    path: ./../pkg/receiver/rawk8seventsreceiver
  # Upstream receivers:

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.57.2

  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/activedirectorydsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/aerospikereceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/apachereceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/bigipreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/carbonreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/cloudfoundryreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/couchdbreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/expvarreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/flinkmetricsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudspannerreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/iisreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/influxdbreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkametricsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/memcachedreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nsxtreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/opencensusreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/podmanreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/riakreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/saphanareceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sapmreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/signalfxreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/skywalkingreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/udplogreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/wavefrontreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowseventlogreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zookeeperreceiver v0.57.2"

extensions:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/extension/sumologicextension v0.0.0-00010101000000-000000000000"
    path: ./../pkg/extension/sumologicextension

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/extension/ballastextension
    gomod: go.opentelemetry.io/collector v0.57.2
  - import: go.opentelemetry.io/collector/extension/zpagesextension
    gomod: go.opentelemetry.io/collector v0.57.2

  # Upstream extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/asapauthextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/awsproxy v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/httpforwarder v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/dockerobserver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/ecsobserver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/ecstaskobserver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/hostobserver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/k8sobserver v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/sigv4authextension v0.57.2"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.57.2"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.57.2"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/dbstorage"


# Replacement paths are relative to the output_path (location of source files)
replaces:
  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver@v0.57.2 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza => github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza v0.57.2

  # ----------------------------------------------------------------------------
  # Needed for telegrafreceiver
  - github.com/influxdata/telegraf => github.com/SumoLogic/telegraf v1.22.0-sumo-4

  # For now, cherry-picked changes are being used:
  # commit: https://github.com/SumoLogic/opentelemetry-collector-contrib/commit/049c70829f005bcd13ed4253de09afe400308df5
  # branch: https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/v0.57.2-filterprocessor
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal => github.com/SumoLogic/opentelemetry-collector-contrib/internal/coreinternal 049c70829f005bcd13ed4253de09afe400308df5
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/attributesprocessor 049c70829f005bcd13ed4253de09afe400308df5
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/resourceprocessor 049c70829f005bcd13ed4253de09afe400308df5

  # Google renamed their org from `googleapis` to `google`, and for `gnostic` this happened in v0.5.6
  # However, kubernetes/client-go still uses the old name for v0.5.5, and this causes go mod to complain
  # Replace this here instead of modifying indirect dependencies in packages, as it's more robust
  - github.com/googleapis/gnostic => github.com/google/gnostic v0.5.5

  # This is to make sure we build the with the sumologicextension from the tree.
  # The reason this is needed is that sumologicexporter depends on sumologicextension in its go.mod.
  # We add a dependency in the builder config in this file but only for a particular (placeholder)
  # version which gets then translated into a replace in go.mod file.
  # This does not replace the version that sumologicexporter depends on.
  - github.com/SumoLogic/sumologic-otel-collector/pkg/extension/sumologicextension => ../../pkg/extension/sumologicextension
