dist:
  name: otelcol-sumo
  description: Sumo Logic OpenTelemetry Collector distribution

  # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  module: github.com/SumoLogic/sumologic-otel-collector

  # the OpenTelemetry Collector version to use as base for the distribution.
  otelcol_version: 0.48.0
  # the path to write the output (sources and binary).
  output_path: ./cmd

exporters:
  # Exporters with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/exporter/sumologicexporter v0.0.0-00010101000000-000000000000"
    path: ./../pkg/exporter/sumologicexporter

  # Upstream exporters:

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.48.0
  - import: go.opentelemetry.io/collector/exporter/otlpexporter
    gomod: go.opentelemetry.io/collector v0.48.0
  - import: go.opentelemetry.io/collector/exporter/otlphttpexporter
    gomod: go.opentelemetry.io/collector v0.48.0

  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/carbonexporter v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.48.0"

processors:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/cascadingfilterprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/cascadingfilterprocessor
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/k8sprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sourceprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/sourceprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sumologicschemaprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/sumologicschemaprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/sumologicsyslogprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/sumologicsyslogprocessor
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/metricfrequencyprocessor v0.0.0-00010101000000-000000000000"
    path: ./../pkg/processor/metricfrequencyprocessor

  # Upstream processors:

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.48.0
  - import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
    gomod: go.opentelemetry.io/collector v0.48.0

  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanprocessor v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.48.0"

receivers:
  # Receivers with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/receiver/telegrafreceiver v0.0.0-00010101000000-000000000000"
    path: ./../pkg/receiver/telegrafreceiver

  # Upstream receivers:

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.48.0

  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/carbonreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudspannerreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkametricsreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/opencensusreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/podmanreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sapmreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/signalfxreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/udplogreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/wavefrontreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zookeeperreceiver v0.48.0"

extensions:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/SumoLogic/sumologic-otel-collector/pkg/extension/sumologicextension v0.0.0-00010101000000-000000000000"
    path: ./../pkg/extension/sumologicextension

  # Since include-code was removed we need to manually add all core components that we want to include:
  # https://github.com/open-telemetry/opentelemetry-collector/pull/4616
  - import: go.opentelemetry.io/collector/extension/ballastextension
    gomod: go.opentelemetry.io/collector v0.48.0
  - import: go.opentelemetry.io/collector/extension/zpagesextension
    gomod: go.opentelemetry.io/collector v0.48.0

  # Upstream receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.48.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.48.0"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage"


# Replacement paths are relative to the output_path (location of source files)
replaces:
  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver@v0.48.0 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza => github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza v0.48.0

  # ----------------------------------------------------------------------------
  # Needed for telegrafreceiver
  - github.com/influxdata/telegraf => github.com/SumoLogic/telegraf v1.22.0-sumo-2

  # TODO: remove this when:
  # - regexp log filtering is released upstream:
  #   PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5680
  # - expr log filtering is merged and released upstream:
  #   PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5680
  # - support for regexp for delete and hash actions for attribute attraction
  #   PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5750
  #
  # For now, cherry-picked changes are being used:
  # commit: https://github.com/SumoLogic/opentelemetry-collector-contrib/commit/bdf80f94cd989542c4e550b58569674f226c31d0
  # branch: https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/v0.48.0-filterprocessor
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/filterprocessor bdf80f94cd989542c4e550b58569674f226c31d0
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal => github.com/SumoLogic/opentelemetry-collector-contrib/internal/coreinternal bdf80f94cd989542c4e550b58569674f226c31d0
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/attributesprocessor bdf80f94cd989542c4e550b58569674f226c31d0
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor => github.com/SumoLogic/opentelemetry-collector-contrib/processor/resourceprocessor bdf80f94cd989542c4e550b58569674f226c31d0

  # Google renamed their org from `googleapis` to `google`, and for `gnostic` this happened in v0.5.6
  # However, kubernetes/client-go still uses the old name for v0.5.5, and this causes go mod to complain
  # Replace this here instead of modifying indirect dependencies in packages, as it's more robust
  - github.com/googleapis/gnostic => github.com/google/gnostic v0.5.5

  # This is to make sure we build the with the sumologicextension from the tree.
  # The reason this is needed is that sumologicexporter depends on sumologicextension in its go.mod.
  # We add a dependency in the builder config in this file but only for a particular (placeholder)
  # version which gets then translated into a replace in go.mod file.
  # This does not replace the version that sumologicexporter depends on.
  - github.com/SumoLogic/sumologic-otel-collector/pkg/extension/sumologicextension => ../../pkg/extension/sumologicextension
