dist:
  # name: otelcol-sumo # name of the binary produced. Optional, specified in Makefile for each platform.
  description: Sumo Logic OpenTelemetry Collector distribution

  # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  module: github.com/SumoLogic/opentelemetry-collector-builder

  # the OpenTelemetry Collector version to use as base for the distribution.
  otelcol_version: 0.27.0
  # the path to write the output (sources and binary).
  output_path: ./cmd

exporters:
  # Exporters with non-upstreamed changes:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sumologicexporter v0.27.0"
  # Upstream exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.27.0"

processors:
  # Processors with non-upstreamed changes:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/cascadingfilterprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/sourceprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/sumologicsyslogprocessor v0.27.0"
  # Upstream processors:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.27.0"

receivers:
  # Receivers with non-upstreamed changes:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/telegrafreceiver v0.27.0"
  # Upstream receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.27.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.27.0"

extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/sumologicextension v0.27.0"

# Replacement paths are relative to the output_path (location of source files)
replaces:
  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver@v0.27.0 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza => github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza v0.27.0

  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver@v0.27.0 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.0.0-00010101000000-000000000000 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage => github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.27.0

  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor@v0.27.0 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig => github.com/open-telemetry/opentelemetry-collector-contrib/internal/k8sconfig v0.27.0

  # This is needed because of:
  # failed to download go modules: exit status 1.
  # Output: "go: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor@v0.27.0 requires
  #  github.com/open-telemetry/opentelemetry-collector-contrib/pkg/batchpersignal@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000"
  - github.com/open-telemetry/opentelemetry-collector-contrib/pkg/batchpersignal => github.com/open-telemetry/opentelemetry-collector-contrib/pkg/batchpersignal v0.27.0

  # ----------------------------------------------------------------------------
  # Customized receivers
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/telegrafreceiver => ./../../pkg/receiver/telegrafreceiver
  - github.com/influxdata/telegraf => github.com/sumologic/telegraf v1.19.0-sumo

  # ----------------------------------------------------------------------------
  # Customized exporters
  - github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sumologicexporter => ./../../pkg/exporter/sumologicexporter

  # ----------------------------------------------------------------------------
  # Customized extensions
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/sumologicextension => ./../../pkg/extension/sumologicextension

  # ----------------------------------------------------------------------------
  # Customized processors
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/cascadingfilterprocessor => ./../../pkg/processor/cascadingfilterprocessor
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/sourceprocessor => ./../../pkg/processor/sourceprocessor
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor => ./../../pkg/processor/k8sprocessor
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/sumologicsyslogprocessor => ./../../pkg/processor/sumologicsyslogprocessor

  # ----------------------------------------------------------------------------
  # Customized core
  - go.opentelemetry.io/collector => github.com/SumoLogic/opentelemetry-collector v0.27.0-sumo-1

  # ----------------------------------------------------------------------------
  # Customized log collection
  # ToDo: Remove after listed PRs are in upstream.
  # - https://github.com/open-telemetry/opentelemetry-log-collection/pull/189
  # - https://github.com/open-telemetry/opentelemetry-log-collection/pull/212
  - github.com/open-telemetry/opentelemetry-log-collection => github.com/SumoLogic/opentelemetry-log-collection v0.18.1-0.20210707064329-e67e78e10a47

  # Needed due to https://github.com/golang/go/issues/46645 present in go1.17-beta1
  # and in go1.17rc1.
  #
  # TODO: remove when this is fixed in newer go versions.
  - golang.org/x/sys => golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c
