extensions:
  sumologic:
    install_token: ${SUMOLOGIC_INSTALL_TOKEN}
    collector_name: ${SUMOLOGIC_COLLECTOR_NAME}

receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      load:

exporters:
  sumologic:

service:
  extensions: [sumologic]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [sumologic]
