receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      load:

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [logging]
