name: Setup Test Environment

description: |
  This action sets up the environment for running tests in the Sumo Logic
  OpenTelemetry Collector (OTC) project. It installs necessary tools and
  dependencies required for testing, including Go JUnit Report.

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-make-environment

    - name: Install Go JUnit Report
      shell: bash
      run: make install-go-junit-report

    - name: Install gotestsum
      shell: bash
      run: make install-gotestsum
