- hosts: sumologic_otel_collector_hosts
  become: true
  gather_facts: True
  vars_files:
    - vars/default.yaml
  tasks:
    - name: "Set architecture to amd64 (x86_64), architecture: {{ ansible_architecture }}"
      set_fact:
         binary_arch: "amd64"
      when: ansible_architecture == 'x86_64'

    - name: "Set architecture to arm64, architecture: {{ ansible_architecture }}"
      set_fact:
         binary_arch: "arm64"
      when: ansible_architecture == 'aarch64' or ansible_architecture == 'arm64'

    - name: "Set OS to linux, OS family: {{ ansible_os_family }}"
      set_fact:
         binary_os: "linux"
      when: 
        - ansible_os_family != 'Windows'
        - ansible_os_family != 'Darwin'

    - name: "Set OS to MacOS, OS family: {{ ansible_os_family }}"
      set_fact:
         binary_os: "darwin"
      when: 
        - ansible_os_family == 'Darwin'
    
    - name: "Installing binary, OS: {{ binary_os }}, architecture: {{ binary_arch }}"
      get_url:
        url: "https://github.com/SumoLogic/sumologic-otel-collector/releases/download/v{{sumologic_otel_collector.version}}/otelcol-sumo-{{ sumologic_otel_collector.version }}-{{ binary_os }}_{{ binary_arch }}"
        dest: /usr/local/bin/otelcol-sumo
        mode: 0755 
      when: 
        - ansible_architecture == 'x86_64' or ansible_architecture == 'aarch64' or ansible_architecture == 'arm64'
        - ansible_os_family != 'Windows'
