include:
  - ../../docker-compose.common.yml

services:
  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 5s

  consumer:
    build:
      context: .
      additional_contexts:
        ca-certificates: service:ca-certificates
      dockerfile: dockerfiles/consumer/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./cmd/consumer/
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URI: amqp://rabbitmq:rabbitmq@rabbitmq:5672

  publisher:
    build:
      context: .
      additional_contexts:
        ca-certificates: service:ca-certificates
      dockerfile: dockerfiles/publisher/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./cmd/publisher/
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URI: amqp://rabbitmq:rabbitmq@rabbitmq:5672

  otel-collector:
    build:
      context: .
      additional_contexts:
        contrib: ../../contrib
        ca-certificates: service:ca-certificates
      dockerfile: ../../dockerfiles/otelcol/Dockerfile
    container_name: otel-collector
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8889:8889
    environment:
      PROMETHEUS_ENDPOINT: :8889
      RABBITMQ_ENDPOINT: http://rabbitmq:15672
      RABBITMQ_USERNAME: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
    volumes:
      - ./otelcol-config.yml:/etc/otelcol/config.yaml
