// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("lookup")
	ScopeName = "github.com/SumoLogic/sumologic-otel-collector/pkg/processor/lookupprocessor"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
