name: Get next available version

on:
  workflow_call:
    outputs:
      version:
        description: "The next unused version to use"
        value: ${{ jobs.get-version.outputs.version }}

defaults:
  run:
    shell: bash

jobs:
  get-version:
    name: Get application version for this revision
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get-version
        run: |
          version=$(./ci/get_version.sh full | xargs)-$(git rev-parse HEAD | xargs)
          echo "version=${version}" > $GITHUB_OUTPUT

      - name: Print version
        run: echo ::notice title=Version::${{ steps.get-version.outputs.version }}
