name: Update docs After Renovate

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to update"
        required: true
        default: "main"

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Run document update script
        run: |
          chmod +x .github/renovate.sh
          .github/renovate.sh

      - name: Commit and push document changes
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: update docs after dependency upgrade" || echo "No changes to commit"
          git push origin "$HEAD_REF"
