name: sign

on:
  pull_request:
    branches:
      - '**'

jobs:
  stuff:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          # The certificates in a PKCS12 file encoded as a base64 string
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - name: Install gon via HomeBrew for code signing and app notarization
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - name: Sign the mac binaries with Gon
        env:
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        working-directory: ./otelcolbuilder/
        run: gon -log-level=debug .gon_config2.json

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: otelcolbuilder/cmd/otelcol-sumo.dmg
