name: Run tests

on:
  workflow_call:
    inputs:
      fips:
        description: Run with FIPS enabled
        default: false
        type: boolean
      go-version:
        description: The version of Go to use.
        type: string
        required: true
      runs-on:
        default: ubuntu-24.04
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go
        with:
          version: ${{ inputs.go-version }}
          cache-dependency-paths: |
            **/*.sum
            otelcolbuilder/.otelcol-builder.yaml

      - uses: ./.github/actions/setup-test-environment

      # - name: Run package tests
      #   run: make gotest-junit ${{ inputs.fips && 'CGO_ENABLED=1 GOEXPERIMENT=boringcrypto' || '' }}

      - name: Run package tests
        run: make gotest-gotestfmt ${{ inputs.fips && 'CGO_ENABLED=1 GOEXPERIMENT=boringcrypto' || '' }}

      # - name: Print JUnit Reports
      #   run: |
      #     find . -name report.xml -exec cat {} \;

      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: |
            **/report.xml
        if: always()

      # Upload the original go test log as an artifact for later review.
      - name: Upload Original Test Log
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
        if: always()

      # NOTE: There doesn't appear to be a simple way to run post hooks in
      # composite actions. We must unmount the VHDX image after we're done using
      # it but before the post-cache hook runs. We should be able to fix this by
      # converting our setup-vhdx action to NodeJS.
      - name: Unmount Go Cache (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Dismount-VHD -Path ${{ steps.setup-go.outputs.vhdx-path }}
