#################################################################################
# A reusable workflow to run tests for otelcol-sumo across multiple platforms.
#################################################################################

name: Workflow - Test Collector (Multiple Platforms)

on:
  workflow_call:
    inputs:
      go-version:
        description: The version of Go to use.
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: >
      ${{ matrix.runs-on }} ${{ matrix.fips == true && '(FIPS)' || '' }}
    uses: ./.github/workflows/workflow-test-otelcol-platform.yml
    with:
      fips: ${{ matrix.fips == true }}
      go-version: ${{ inputs.go-version }}
      runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-24.04
          - runs-on: ubuntu-24.04
            fips: true
          - runs-on: macos-15
          - runs-on: windows-2025
