name: Run tests (otelcol-config)

on:
  workflow_call:
    inputs:
      arch_os:
        description: Architecture and OS in the form "{arch}_{os}". See GOARCH and GOOS for accepted values.
        default: linux_amd64
        type: string
      boringcrypto:
        description: Run with BoringCrypto enabled
        default: false
        type: boolean
      go-version:
        description: The version of Go to use.
        type: string
        required: true
      only-if-changed:
        description: Run only if relevant files changed.
        default: false
        type: boolean
      runs-on:
        default: ubuntu-24.04
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test (otelcol-config)
    runs-on: ${{ inputs.runs-on }}
    env:
      BORINGCRYPTO_SUFFIX: ${{ inputs.boringcrypto && '-boringcrypto' || '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go
        with:
          version: ${{ inputs.go-version }}
          cache-name: otelcol-config-go-cache
          cache-dependency-paths: |
            pkg/tools/otelcol-config/go.sum

      - name: Run tests
        run: make test ${{ inputs.boringcrypto && 'CGO_ENABLED=1 GOEXPERIMENT=boringcrypto' || '' }}
        working-directory: ./pkg/tools/otelcol-config
