name: Run tests

on:
  workflow_call:
    inputs:
      arch_os:
        description: Architecture and OS in the form "{arch}_{os}". See GOARCH and GOOS for accepted values.
        default: linux_amd64
        type: string
      boringcrypto:
        description: Run with BoringCrypto enabled
        default: false
        type: boolean
      runs-on:
        default: ubuntu-24.04
        type: string
      only-if-changed:
        description: Run only if relevant files changed.
        default: false
        type: boolean

defaults:
  run:
    shell: bash

env:
  GO_VERSION: "1.23.0"

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.runs-on }}
    env:
      BORINGCRYPTO_SUFFIX: ${{ inputs.boringcrypto && '-boringcrypto' || '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go
        with:
          version: ${{ env.GO_VERSION }}

      - name: Setup yq
        uses: ./.github/actions/setup-yq

      - name: Setup opentelemetry-collector-builder
        uses: ./.github/actions/setup-opentelemetry-collector-builder

      - name: Run package tests
        run: make gotest ${{ inputs.boringcrypto && 'CGO_ENABLED=1 GOEXPERIMENT=boringcrypto' || '' }}
