#################################################################################
# A reusable workflow to run tests for otelcol-sumo.
#################################################################################

name: Workflow - Test Collector (Single Platform)

on:
  workflow_call:
    inputs:
      fips:
        description: Run with FIPS enabled
        default: false
        type: boolean
      go-version:
        description: The version of Go to use.
        type: string
        required: true
      runs-on:
        default: ubuntu-24.04
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    name: >
      ${{ inputs.runs-on }} ${{ inputs.fips == true && '(FIPS)' || '' }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: ./.github/actions/setup-go
        with:
          version: ${{ inputs.go-version }}
          cache-dependency-paths: |
            **/*.sum
            otelcolbuilder/.otelcol-builder.yaml

      - uses: ./.github/actions/setup-test-environment

      - name: Run tests
        run: |
          make gotest ${{
            inputs.fips && 'CGO_ENABLED=1 GOEXPERIMENT=boringcrypto' || ''
          }}

      # NOTE: There doesn't appear to be a simple way to run post hooks in
      # composite actions. We must unmount the VHDX image after we're done using
      # it but before the post-cache hook runs. We should be able to fix this by
      # converting our setup-vhdx action to NodeJS.
      - name: Unmount Go Cache (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Dismount-VHD -Path ${{ steps.setup-go.outputs.vhdx-path }}
