name: Push container image indexes

on:
  workflow_call:
    inputs:
      target:
        description: |
          The bake target to build. The product name will be used as the target
          when target is not set.
        type: string
      version:
        description: The version of OTC the images are for.
        type: string
        required: true
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      dockerhub-login:
        required: true
      dockerhub-password:
        required: true

defaults:
  run:
    shell: bash

jobs:
  push:
    name: Push
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Show Buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 663229565520.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN_DEV }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_DEV }}

      - uses: actions/download-artifact@v4
        with:
          pattern: "manifest_${{ inputs.target }}_*"
          path: manifests
          merge-multiple: true

      - name: Determine source images
        run: |
          jq -jf ci/jq/manifest-sources.jq --arg target ${{ inputs.target }} \
          manifests/*.json > sources.txt

          cat sources.txt

      - name: Determine tags (ECR)
        env:
          REPO_BASE: 663229565520.dkr.ecr.us-east-1.amazonaws.com
          REPO_ORG: sumologic
          REPO_NAME: sumologic-otel-collector-ci-builds
        run: |
          REPO="${REPO_BASE}/${REPO_ORG}/${REPO_NAME}"
          echo '${{ inputs.tags }}' | jq -jf ci/jq/tags.jq --arg url "$REPO" > ecr-tags.txt

      - name: Determine tags (Docker Hub)
        env:
          REPO_BASE: docker.io
          REPO_ORG: sumologic
          REPO_NAME: sumologic-otel-collector-ci-builds
        run: |
          REPO="${REPO_BASE}/${REPO_ORG}/${REPO_NAME}"
          echo '${{ inputs.tags }}' | jq -jf ci/jq/tags.jq --arg url "$REPO" > dh-tags.txt

      - name: Create multiplatform image index (ECR)
        run: |
          docker buildx imagetools create $(cat sources.txt) $(cat ecr-tags.txt)

      - name: Create multiplatform image index (Docker Hub)
        run: |
          docker buildx imagetools create $(cat sources.txt) $(cat dh-tags.txt)
