name: Build Otelcol Config Tool

on:
  workflow_call:
    inputs:
      fips:
        description: Build binary with FIPS support
        default: false
        type: boolean
      go-version:
        description: The version of Go to use.
        type: string
        required: true
      platform:
        description: |
          Platform (Operating System and CPU architecture) in the form
          "{os}_{arch}". See GOOS and GOARCH for accepted values.
        default: linux_amd64
        type: string
      runs-on:
        default: ubuntu-24.04
        type: string
      signing-enabled:
        default: true
        type: boolean
    secrets:
      apple_developer_certificate_p12_base64:
        required: false
      apple_developer_certificate_password:
        required: false
      app_store_connect_password:
        required: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    env:
      FIPS_SUFFIX: ${{ inputs.fips && '-fips' || '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/parse-go-platform
        id: platform
        with:
          platform: ${{ inputs.platform }}

      - name: Setup Go Distribution
        id: setup-go
        uses: ./.github/actions/setup-go
        with:
          version: ${{ inputs.go-version }}
          cache-name: otelcol-config-go-cache
          cache-dependency-paths: |
            pkg/tools/otelcol-config/go.sum

      - uses: ./.github/actions/setup-build-environment
        if: inputs.signing-enabled
        with:
          apple-signing-certificate-p12-base64: ${{ secrets.apple_developer_certificate_p12_base64 }}
          apple-signing-certificate-password: ${{ secrets.apple_developer_certificate_password }}
          fips: ${{ inputs.fips }}

      - name: Build
        if: "! inputs.fips"
        run: make otelcol-config-${{ inputs.platform }}
        working-directory: ./pkg/tools/otelcol-config

      - name: Setup Toolchain
        uses: ./.github/actions/setup-toolchain
        if: inputs.fips && steps.platform.outputs.os == 'linux'
        with:
          platform: ${{ inputs.platform }}

      - name: Build (FIPS)
        if: inputs.fips && steps.platform.outputs.os == 'linux'
        run: |
          CC=$(find /opt/toolchain/bin -type f -name "*-linux-musl-gcc")
          test "$CC"
          echo "Using toolchain: $CC"
          make otelcol-config-${{ inputs.platform }} \
            FIPS_SUFFIX="-fips" \
            CGO_ENABLED="1" \
            CC="$CC" \
            LDFLAGS="-linkmode external -extldflags '-static'"
        working-directory: ./pkg/tools/otelcol-config

      - name: Set binary name
        uses: ./.github/actions/determine-binary-name
        id: set-binary-name
        with:
          fips: ${{ inputs.fips }}
          name: otelcol-config
          platform: ${{ inputs.platform }}

      - name: Show file info
        working-directory: ./pkg/tools/otelcol-config
        run: |
          file ${{ steps.set-binary-name.outputs.name }}

      - name: Show ldd info
        if: steps.platform.outputs.os == 'linux'
        working-directory: ./pkg/tools/otelcol-config
        run: |
          ldd ${{ steps.set-binary-name.outputs.name }} || true

      - uses: ./.github/actions/show-fips-symbols
        if: inputs.fips
        with:
          name: ${{ steps.set-binary-name.outputs.name }}
          os: ${{ steps.platform.outputs.os }}
          working-directory: ./pkg/tools/otelcol-config

      - name: Sign the mac binaries
        if: runner.os == 'macOS' && inputs.signing-enabled
        env:
          AC_PASSWORD: ${{ secrets.app_store_connect_password }}
        working-directory: ./pkg/tools/otelcol-config
        run: make ${{ inputs.platform }}-sign

      - name: Store binary as action artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-binary-name.outputs.name }}
          path: ./pkg/tools/otelcol-config/${{ steps.set-binary-name.outputs.name }}
          if-no-files-found: error

      - name: Store macOS .dmg as action artifact
        uses: actions/upload-artifact@v4
        if: runner.os == 'macOS'
        with:
          name: ${{ steps.set-binary-name.outputs.name }}.dmg
          path: ./pkg/tools/otelcol-config/${{ steps.set-binary-name.outputs.name }}.dmg
          if-no-files-found: error
